on: [push]

name: mabl GitHub actions test

jobs:
  test:
    name: mabl Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Functional test deployment
        id: mabl-test-deployment
        uses: mablhq/github-run-tests-action@v1
        env:
          MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
        with:
          application-id: PD1IaPsJm9CyMf2A2I3gSQ-a
          environment-id: Ojc0fnJOoTBgSEZSHUCrhQ-e

